# Generated by Django 4.2.2 on 2023-07-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_publicacion_rename_curso_historiaspersonales_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Meetups',
        ),
    ]
