# Generated by Django 4.2.2 on 2023-07-08 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_profesor_meetups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaspersonales',
            name='camada',
        ),
        migrations.RemoveField(
            model_name='historiaspersonales',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='historiaspersonales',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='meetups',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='meetups',
            name='email',
        ),
        migrations.RemoveField(
            model_name='meetups',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='preguntasyrespuestas',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='preguntasyrespuestas',
            name='entregada',
        ),
        migrations.RemoveField(
            model_name='preguntasyrespuestas',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='recursosyconsejos',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='recursosyconsejos',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recursosyconsejos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='historiaspersonales',
            name='contenido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historiaspersonales',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='historiaspersonales',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='meetups',
            name='contenido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='meetups',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='meetups',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preguntasyrespuestas',
            name='contenido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preguntasyrespuestas',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='preguntasyrespuestas',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recursosyconsejos',
            name='contenido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recursosyconsejos',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='recursosyconsejos',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
