# Generated by Django 4.2.2 on 2023-07-09 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_remove_historiaspersonales_camada_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
