# Generated by Django 4.2.2 on 2023-07-10 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_delete_publicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recursosyconsejos',
        ),
    ]
