# Generated by Django 4.2.2 on 2023-07-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historiaspersonales',
        ),
        migrations.DeleteModel(
            name='Preguntasyrespuestas',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='link',
            field=models.URLField(),
        ),
    ]
