# Generated by Django 4.2.2 on 2023-07-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_pagina_delete_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='subtitle',
            field=models.CharField(default=0, max_length=200, verbose_name='Subtítulo'),
        ),
    ]
