# Generated by Django 4.2.2 on 2023-07-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_pagina_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='subtitle',
            field=models.CharField(default='Subtítulo', max_length=200, verbose_name='Subtítulo'),
        ),
    ]
